phi-2:
  prompt_template: "phi-2/prompt.txt"
  # fn_completions: "vllm_local_completions"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "/mntcephfs/data/med/chenghao/models/phi-2"
    # "microsoft/phi-2"
    model_kwargs:
      torch_dtype: "float16"
      # tp: 1
      # tokenizer_mode: "auto"
      trust_remote_code: True
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "Phi 2"
  link: "https://huggingface.co/microsoft/phi-2"


# origional use vllm 

# is like this

# phi-2:
#   prompt_template: "phi-2/prompt.txt"
#   fn_completions: "vllm_local_completions"
#   completions_kwargs:
#     model_name: "/mntcephfs/data/med/chenghao/models/phi-2"
#     # "microsoft/phi-2"
#     model_kwargs:
#       torch_dtype: "float16"
#       tp: 1
#       tokenizer_mode: "auto"
#       trust_remote_code: True
#     max_new_tokens: 2048
#     temperature: 0.7
#     top_p: 1.0
#     do_sample: True
#   pretty_name: "Phi 2"
#   link: "https://huggingface.co/microsoft/phi-2"


# llama-2-7b-chat-hf:
#   prompt_template: "llama-2-7b-chat-hf/prompt.txt"
#   fn_completions: "huggingface_local_completions"
#   completions_kwargs:
#     model_name: "/mntcephfs/data/med/guimingchen/models/general/llama2-7b-chat-hf"
#     # model_name: "meta-llama/Llama-2-7b-chat-hf"
#     model_kwargs:
#       torch_dtype: 'float16'
#       trust_remote_code: True
#     max_new_tokens: 2048
#     temperature: 0.7
#     top_p: 1.0
#     do_sample: True
#   pretty_name: "LLaMA2 Chat 7B"
#   link: "https://ai.meta.com/llama/"
