Qwen-1_8B:
  prompt_template: "Qwen-1_8B/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "/mntcephfs/data/med/chenghao/models/Qwen-1_8B"
    requires_chatml: True
    model_kwargs:
      torch_dtype: "bfloat16"
      trust_remote_code: True
      tokenizer_mode: "auto"
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "Qwen 1.8B"
  link: "https://huggingface.co/Qwen/Qwen-1_8B"


# Qwen-1_8B:
#   prompt_template: "Qwen-1_8B/prompt.txt"
#   # fn_completions: "vllm_local_completions"
#   fn_completions: "huggingface_local_completions"
#   completions_kwargs:
#     model_name: "/mntcephfs/data/med/chenghao/models/Qwen-1_8B"
#     # "microsoft/phi-2"
#     model_kwargs:
#       # torch_dtype: "float16"
#       # tp: 1
#       # tokenizer_mode: "auto"
#       trust_remote_code: True
#     max_new_tokens: 2048
#     temperature: 0.7
#     top_p: 1.0
#     do_sample: True
#   pretty_name: "Qwen 1.8B"
#   link: "https://huggingface.co/Qwen/Qwen-1_8B"
