llama-2-7b-chat-hf:
  prompt_template: "falcon-rw-1b/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "/mntcephfs/data/med/chenghao/models/falcon-rw-1b"
    # model_name: "meta-llama/Llama-2-7b-chat-hf"
    model_kwargs:
      # torch_dtype: 'float16'
      trust_remote_code: True
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "Falcon-RW-1B"
  link: "tiiuae/falcon-rw-1b"
